apiVersion: apps/v1
kind: Deployment
metadata:
  name: graphql-deployment
  labels:
    app: graphql
spec:
  replicas: 2
  selector:
    matchLabels:
      app: graphql
  minReadySeconds: 10
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: graphql
    spec:
      containers:
        - name: graphql
          image: cgmartinez/chat-app:latest
          resources:
            requests:
              memory: '64Mi'
              cpu: '250m'
            limits:
              memory: '128Mi'
              cpu: '500m'
          ports:
            - containerPort: 8081
